<?

// sped_matriz
/* Bloco Descrição
0 Abertura, Identificação e Referências
C Documentos Fiscais I  Mercadorias (ICMS/IPI)
D Documentos Fiscais II  Serviços (ICMS)
E Apuração do ICMS e do IPI
H Inventário Físico
1 Outras Informações
9 Controle e Encerramento do Arquivo Digital


*/
class MATRIZ_SPED {


         function m_sped_efd_registros() {

                            $l= array(
"0000" => "REGISTRO 0000: ABERTURA DO ARQUIVO DIGITAL E IDENTIFICAÇÃO DA ENTIDADE",
"0001" => "REGISTRO 0001: ABERTURA DO BLOCO 0",
"0005" => "REGISTRO 0005: DADOS COMPLEMENTARES DA ENTIDADE",
"0015" => "REGISTRO 0015: DADOS DO CONTRIBUINTE SUBSTITUTO #",
"0100" => "REGISTRO 0100: DADOS DO CONTABILISTA",
"0150" => "REGISTRO 0150: TABELA DE CADASTRO DO PARTICIPANTE",
"0175" => "REGISTRO 0175: ALTERAÇÃO DA TABELA DE CADASTRO DE PARTICIPANTE #",
"0190" => "REGISTRO 0190: IDENTIFICAÇÃO DAS UNIDADES DE MEDIDA",
"0200" => "REGISTRO 0200: TABELA DE IDENTIFICAÇÃO DO ITEM (PRODUTO E SERVIÇOS)",
"0205" => "REGISTRO 0205: ALTERAÇÃO DO ITEM #",
"0206" => "REGISTRO 0206: CÓDIGO DE PRODUTO CONFORME TABELA PUBLICADA PELA ANP (COMBUSTÍVEIS) #",
"0220" => "REGISTRO 0220: FATORES DE CONVERSÃO DE UNIDADES",
"0300" => "REGISTRO 0300: CADASTRO DE BENS OU COMPONENTES DO ATIVO IMOBILIZADO #",
"0305" => "REGISTRO 0305  INFORMAÇÃO SOBRE A UTILIZAÇÃO DO BEM #",
"0400" => "REGISTRO 0400: TABELA DE NATUREZA DA OPERAÇÃO/PRESTAÇÃO",
"0450" => "REGISTRO 0450: TABELA DE INFORMAÇÃO COMPLEMENTAR DO DOCUMENTO FISCAL",
"0460" => "REGISTRO 0460: TABELA DE OBSERVAÇÕES DO LANÇAMENTO FISCAL #",
"0500" => "REGISTRO 0500: PLANO DE CONTAS CONTABEIS",
"0600" => "REGISTRO 0600: CENTRO DE CUSTOS #",
"0990" => "REGISTRO 0990: ENCERRAMENTO DO BLOCO 0",
"C001" => "REGISTRO C001: ABERTURA DO BLOCO C",
"C100" => "REGISTRO C100: NOTA FISCAL (01), NOTA FISCAL AVULSA (1B), NOTA FISCAL DE PRODUTOR (04) E NFE (55).",
"C105" => "REGISTRO C105  OPERAÇÕES COM ICMS ST RECOLHIDO PARA UF DIVERSA DO DESTINATÁRIO DO DOCUMENTO FISCAL (CÓDIGO 55). #",
"C110" => "REGISTRO C110: INFORMAÇÃO COMPLEMENTAR DA NOTA FISCAL (CÓDIGO 01, 1B, 04 e 55).",
"C111" => "REGISTRO C111: PROCESSO REFERENCIADO #",
"C112" => "REGISTRO C112: DOCUMENTO DE ARRECADAÇÃO REFERENCIADO #",
"C113" => "REGISTRO C113: DOCUMENTO FISCAL REFERENCIADO. #",
"C114" => "REGISTRO C114: CUPOM FISCAL REFERENCIADO. #",
"C115" => "REGISTRO C115: LOCAL DA COLETA E/OU ENTREGA (CÓDIGO 01, 1B E04). #",
"C120" => "REGISTRO C120: OPERAÇÕES DE IMPORTAÇÃO (CÓDIGO 01). #",
"C130" => "REGISTRO C130: ISSQN, IRRF E PREVIDÊNCIA SOCIAL. ",
"C140" => "REGISTRO C140: FATURA (CÓDIGO 01)",
"C141" => "REGISTRO C141: VENCIMENTO DA FATURA (CÓDIGO 01)",
"C160" => "REGISTRO C160: VOLUMES TRANSPORTADOS (CÓDIGO 01 E 04) - EXCETO COMBUSTÍVEIS. #",
"C165" => "REGISTRO C165: OPERAÇÕES COM COMBUSTÍVEIS (CÓDIGO 01). #",
"C170" => "REGISTRO C170: ITENS DO DOCUMENTO (CÓDIGO 01, 1B, 04 e 55)",
"C171" => "REGISTRO C171: ARMAZENAMENTO DE COMBUSTIVEIS (código 01, 55). #",
"C172" => "REGISTRO C172: OPERAÇÕES COM ISSQN (CÓDIGO 01)",
"C173" => "REGISTRO C173: OPERAÇÕES COM MEDICAMENTOS (CÓDIGO 01 e 55). #",
"C174" => "REGISTRO C174: OPERAÇÕES COM ARMAS DE FOGO (CÓDIGO 01). #",
"C175" => "REGISTRO C175: OPERAÇÕES COM VEÍCULOS NOVOS (CÓDIGO 01 e 55). #",
"C176" => "REGISTRO C176: RESSARCIMENTO DE ICMS EM OPERAÇÕES COM SUBSTITUIÇÃO TRIBUTÁRIA (CÓDIGO 01, 55).#",
"C177" => "REGISTRO C177: OPERAÇÕES COM PRODUTOS SUJEITOS A SELO DE CONTROLE IPI. #",
"C178" => "OPERAÇÕES COM PRODUTOS SUJEITOS À TRIBUTAÇÀO DE IPI POR UNIDADE OU QUANTIDADE DE PRODUTO. #",
"C179" => "REGISTRO C179: INFORMAÇÕES COMPLEMENTARES ST (CÓDIGO 01).",
"C190" => "REGISTRO C190: REGISTRO ANALÍTICO DO DOCUMENTO (CÓDIGO 01,1B, 04 E 55).",
"C195" => "REGISTRO C195: OBSERVAÇOES DO LANÇAMENTO FISCAL (CÓDIGO 01,1B E 55)",
"C197" => "REGISTRO C197: OUTRAS OBRIGAÇÕES TRIBUTÁRIAS, AJUSTES E INFORMAÇÕES DE VALORES PROVENIENTES DE DOCUMENTO FISCAL.",
// OUTROS C...
"C990" => "REGISTRO C990: ENCERRAMENTO DO BLOCO C",
// OUITROS D
// BLOCO E: APURAÇÃO DO ICMS E DO IPI
"E001" => "REGISTRO E001: ABERTURA DO BLOCO E",
"E100" => "REGISTRO E100: PERÍODO DA APURAÇÃO DO ICMS.",
"E110" => "REGISTRO E110: APURAÇÃO DO ICMS  OPERAÇÕES PRÓPRIAS.",
"E111" => "REGISTRO E111: AJUSTE/BENEFÍCIO/INCENTIVO DA APURAÇÃO DO ICMS.",
"E112" => "REGISTRO E112: INFORMAÇÕES ADICIONAIS DOS AJUSTES DA APURAÇÃO DO ICMS.",
"E113" => "REGISTRO E113: INFORMAÇÕES ADICIONAIS DOS AJUSTES DA APURAÇÃO DO ICMS  IDENTIFICAÇÃO DOS DOCUMENTOS FISCAIS.",
"E115" => "REGISTRO E115: INFORMAÇÕES ADICIONAIS DA APURAÇÃO  VALORES DECLARATÓRIOS.",
"E116" => "REGISTRO E116: OBRIGAÇÕES DO ICMS A RECOLHER  OPERAÇÕES PRÓPRIAS.",
"E200" => "REGISTRO E200: PERÍODO DA APURAÇÃO DO ICMS - SUBSTITUIÇÃO TRIBUTÁRIA.",
"E210" => "REGISTRO E210: APURAÇÃO DO ICMS  SUBSTITUIÇÃO TRIBUTÁRIA.",
"E220" => "REGISTRO E220: AJUSTE/BENEFÍCIO/INCENTIVO DA APURAÇÃO DO ICMS SUBSTITUIÇÃO TRIBUTÁRIA.",
"E230" => "REGISTRO E230: INFORMAÇÕES ADICIONAIS DOS AJUSTES DA APURAÇÃO DO ICMS SUBSTITUIÇÃO TRIBUTÁRIA.",
"E240" => "REGISTRO E240: INFORMAÇÕES ADICIONAIS DOS AJUSTES DA APURAÇÃO DO ICMS SUBSTITUIÇÃO TRIBUTÁRIA  IDENTIFICAÇÃO DOS DOCUMENTOS FISCAIS.",
"E250" => "REGISTRO E250: OBRIGAÇÕES DO ICMS A RECOLHER  SUBSTITUIÇÃO TRIBUTÁRIA.",
"E500" => "REGISTRO E500: PERÍODO DE APURAÇÃO DO IPI.",
"E510" => "REGISTRO E510: CONSOLIDAÇÃO DOS VALORES DO IPI.",
"E520" => "REGISTRO E520: APURAÇÃO DO IPI.",
"E530" => "REGISTRO E530: AJUSTES DA APURAÇÃO DO IPI.",
"E990" => "REGISTRO E990: ENCERRAMENTO DO BLOCO E",
// BLOCO G
//BLOCO H: INVENTÁRIO FÍSICO
"H001" => "REGISTRO H001: ABERTURA DO BLOCO H",
"H005" => "REGISTRO H005: TOTAIS DO INVENTÁRIO",
"H010" => "REGISTRO H010: INVENTÁRIO.",
"H990" => "REGISTRO H990: ENCERRAMENTO DO BLOCO H.",
// BLOCO 1
// BLOCO 9: CONTROLE E ENCERRAMENTO DO ARQUIVO DIGITAL

"9001" => "REGISTRO 9001: ABERTURA DO BLOCO 9",
"9900" => "REGISTRO 9900: REGISTROS DO ARQUIVO.",
"9990" => "REGISTRO 9990: ENCERRAMENTO DO BLOCO 9",
"9999" => "REGISTRO 9999: ENCERRAMENTO DO ARQUIVO DIGITAL.",
"XXXX" =>"");


    				return $l;
		}
		
}

?>


